language: ruby

rvm:
 - 2.2.2
 - 2.3
 - 2.4

gemfile:
 - gemfiles/rails-5.0.gemfile
 - gemfiles/rails-5.1.gemfile
 - Gemfile

before_install: "gem update bundler"

script: "bin/test"

notifications:
  email: false
